name: hyperlocal-obs-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - arm_pyart
  - act-atmos
  - matplotlib
  - jupyterlab
  - jupyter-book
  - sphinx-pythia-theme
  - xradar
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas
  - fiona
  - hvplot
  - imageio
  - siphon
  - scikit-learn
  - myst-nb
  - pip
  - pip:
    - ambient-api
    - sage-data-client
    - nexradaws
